export const COUNTRIES = [
  {
    name: 'Brazil',
    code: 'BRA',
    flag: '🇧🇷',
    flagImage: 'brazil.png',
    colors: ['#009c3b', '#ffdf00'],
  },
  {
    name: 'Argentina',
    code: 'ARG',
    flag: '🇦🇷',
    flagImage: 'argentina.png',
    colors: ['#74acdf', '#ffffff'],
  },
  {
    name: 'France',
    code: 'FRA',
    flag: '🇫🇷',
    flagImage: 'france.png',
    colors: ['#002654', '#ed2939'],
  },
  {
    name: 'Germany',
    code: 'DEU',
    flag: '🇩🇪',
    flagImage: 'germany.png',
    colors: ['#000000', '#dd0000'],
  },
  {
    name: 'Spain',
    code: 'ESP',
    flag: '🇪🇸',
    flagImage: 'spain.png',
    colors: ['#c60b1e', '#ffc400'],
  },
  {
    name: 'England',
    code: 'GBR',
    flag: '🏴',
    flagImage: 'england.png',
    colors: ['#ffffff', '#ce1124'],
  },
  {
    name: 'Portugal',
    code: 'PRT',
    flag: '🇵🇹',
    flagImage: 'portugal.png',
    colors: ['#006600', '#ff0000'],
  },
  {
    name: 'Netherlands',
    code: 'NLD',
    flag: '🇳🇱',
    flagImage: 'netherlands.png',
    colors: ['#ff6600', '#ffffff'],
  },
  {
    name: 'Belgium',
    code: 'BEL',
    flag: '🇧🇪',
    flagImage: 'belgium.png',
    colors: ['#000000', '#fdda24'],
  },
  {
    name: 'Italy',
    code: 'ITA',
    flag: '🇮🇹',
    flagImage: 'italy.png',
    colors: ['#009246', '#ffffff'],
  },
  {
    name: 'Mexico',
    code: 'MEX',
    flag: '🇲🇽',
    flagImage: 'mexico.png',
    colors: ['#006847', '#ce1126'],
  },
  {
    name: 'United States',
    code: 'USA',
    flag: '🇺🇸',
    flagImage: 'united-states.png',
    colors: ['#002868', '#bf0a30'],
  },
  {
    name: 'Canada',
    code: 'CAN',
    flag: '🇨🇦',
    flagImage: 'canada.png',
    colors: ['#ff0000', '#ffffff'],
  },
  {
    name: 'Japan',
    code: 'JPN',
    flag: '🇯🇵',
    flagImage: 'japan.png',
    colors: ['#ffffff', '#bc002d'],
  },
  {
    name: 'South Korea',
    code: 'KOR',
    flag: '🇰🇷',
    flagImage: 'south-korea.png',
    colors: ['#003478', '#c60c30'],
  },
];
